#spring.h2.console.enabled = true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:homebanking;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update

spring.data.rest.base-path=/rest

spring.jackson.serialization.INDENT_OUTPUT=true
# Si no encuentra la variable DB_HOST, usará la IP de tu Pi por defecto
spring.datasource.url=jdbc:postgresql://${DB_HOST:192.168.0.250}:5432/mhbank
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
spring.jpa.generate-ddl=true

server.port = 8080
server.address = 0.0.0.0